service: placeholder-generator
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  placeholder:
    handler: handler.placeholder
    events:
      - httpApi:
          path: /{image_name}
          method: get
plugins:
  - serverless-offline
