service: placeholder-generator
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stackTags:
    "project": "placeholder-generator"
  httpApi:
    cors: true

functions:
  placeholder:
    handler: handler.placeholder
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-pillow:1
    events:
      - httpApi:
          path: /{image_name}
          method: get
plugins:
  - serverless-offline
  - serverless-python-requirements

package:
  patterns:
    - "!__pycache__"
    - "!node_modules/**"
    - "!venv"
    - "!package.json"
    - "!yarn.lock"
    - "README.md"
    - ".gitignore"
    - "serverless.yml"